name: My Name Workflow

on: push

jobs:
    first_jobs:
        runs-on: ubuntu-latest
        steps:

        - name: Checkout Repo
          uses: actions/checkout@v5

        - name: List and Read Files
          run: |
            echo "My First Github Action Job"
            ls -ltra
            cat README.md
            
        - name: Generate ASCII Art work
          run: cowsay -f dragon "Run for cover, I am dragon ........... RAWR" >> dragon.txt